### ISSUE TITLE
Image to ASCII converter (Python)

### ISSUE THREAD

**Issue by Vyshhh** [Lavanyasuc31/HactoberFestContribution2024#14]
As a beginner I am very interested to contribute my work to this repo. The algorithm used here takes path of image as input and gives ASCII art of that image and save it as .txt file.  @Lavanyasuc31 can you please assign this to me under hacktoberfest2024 tag.

Thank you

**Comment by Lavanyasuc31** [comment]
Thank you for your interest in contributing! I’m assigning this task to you as part of Hacktoberfest 2024. Please proceed with the implementation.

**Comment by Satyam-nitp** [comment]
Can you assign this to me @Lavanyasuc31

**Comment by Samruddhi345A** [comment]
Hi Please assign to me this task
