### ISSUE TITLE
Issue: Adding new JavaScript project : Calculator

### ISSUE THREAD

**Issue by codeforlifeee** [Lavanyasuc31/HactoberFestContribution2024#22]
Please accept this under Hacktoberfest2024 i will create a pull request for Calculator Project which  i have developed using html, css and javascript.

**Comment by Lavanyasuc31** [comment]
I have assigned this task to you, you can now proceed with the implementation

**Comment by harshitajha4680** [comment]
I'm interested, please assign this to me!

**Comment by rookieanvesh** [comment]
Hey leads! could you please assign this task to me

**Comment by Arushi2S** [comment]
CAN YOU PLZ ASSIGN ME THIS TASK, I WILL CREATE A BASIC CALCULATOR USING CSS ,HTM AND JAVASCRIPT
