### ISSUE TITLE
Document Updation : README.md

### ISSUE THREAD

**Issue by soham0028** [Lavanyasuc31/HactoberFestContribution2024#23]
hello @Lavanyasuc31 ,
the current readme file does not contain following sections :
1. Table of contents for easy access to new contributors
2. featured in 
3. contributors
4. forkers and stargazers 
5. back to top button for easy navigation

Kindly Assign me this issue .

**Comment by Lavanyasuc31** [comment]
hello, it is really a good idea, you can proceed with the implementation

**Comment by soham0028** [comment]
All changes committed .
Please do Review
Thank-you for the opportunity !
