### ISSUE TITLE
Mouse Interaction for Zooming and Panning in SDL Application

### ISSUE THREAD

**Issue by Suchit1938** [Lavanyasuc31/HactoberFestContribution2024#26]
SDL application that involves scrolling and zooming.

Expected Behavior :-

1. Mouse wheel should zoom in and out of the texture using both keyboard and mouse interactions.
2. Left-click drag should pan the view smoothly.
3. Points should move randomly within the texture.

**Comment by Suchit1938** [comment]
Hi plz, assign this to me as I am currently learning SDL2.
and also I am Eager to contribute under hacktoberfest.

**Comment by Lavanyasuc31** [comment]
hey, I have assigned this task to you. You can start implementing now.

**Comment by shrutipuskar** [comment]
plz assign this task to me and also add hactoberfest tag........
