### ISSUE TITLE
Changing the different components of the webpage of expense record

### ISSUE THREAD

**Issue by amanvatss** [Lavanyasuc31/HactoberFestContribution2024#6]
Hi @Lavanyasuc31 

All the that I will resolve :

1. Navbar: You've successfully added a functional navbar with a language dropdown and Home link.
2. Background Image: You added a background image in the CSS, ensuring the correct path for it.
3. Form Functionality: You've implemented a functional expense form with validation for amount, type, and date fields.
4. Expense Display: Added logic to display the entered expense details dynamically on the page after form submission.
5. Styling Improvements: Adjusted styles like form layout and button hover effects to make the page more appealing.

pls assign me this

Thankyou

**Comment by Lavanyasuc31** [comment]
Thank you for your interest in contributing! I’m assigning this task to you as part of Hacktoberfest 2024. Please proceed with the implementation.

**Comment by amanvatss** [comment]
Hi
I am Aman vats.
I recently contributed to the repository of the HacktoberFest Contribution
2024 which is available in the GitHub repository of your's.
But after you assigned me the task, I worked on the project and created a
pull request for the same.

But on the HacktoberFest website It is showing me that this repository is
excluded  from the hacktoberfest.

I attached a screenshot of the same.

Please Kindly look into it matter asap

[image: image.png]
