### ISSUE TITLE
Rajasthan Chatbot Python project

### ISSUE THREAD

**Issue by DevDatir** [Lavanyasuc31/HactoberFestContribution2024#9]
Hey,

I would love to contribute to this repo, please assign me this issue @Lavanyasuc31!
Can you please assign this to me under the hacktoberfest2024 tag?

**Comment by Lavanyasuc31** [comment]
Thank you for your interest in contributing! I’m assigning this task to you as part of Hacktoberfest 2024. Please proceed with the implementation.

**Comment by DevDatir** [comment]
Please review this PR @Lavanyasuc31 !
